In [2]:
#ejercicios de pytorch
import torch

In [3]:
#tensores , en si lo mismo que un array en numpy
V_data = [1, 2, 3, 4, 5]
V = torch.tensor(V_data)
print(V)

tensor([1, 2, 3, 4, 5])


In [4]:
x = torch.randn((3, 4, 5))
print(x)

tensor([[[-0.3641, -0.7534, -1.0666,  0.0947, -3.6514],
         [ 0.1866, -0.2877, -2.2462, -2.1561, -0.1112],
         [-0.4857, -1.0916,  0.6168,  0.9445, -0.8462],
         [-0.3658, -0.8979, -0.6170, -0.0915,  0.9221]],

        [[ 1.1087,  0.1873, -1.0590,  0.6929, -0.6989],
         [ 0.4501, -0.4197, -0.3023,  0.2668,  1.0982],
         [-0.6097, -0.0290,  0.2174,  0.4722,  0.9905],
         [-0.9502,  0.1584, -0.7167, -1.0798,  1.1546]],

        [[ 1.1652, -1.4117,  1.2780, -0.8846,  0.3612],
         [-0.1954, -1.1338,  1.6472,  0.1787, -0.6475],
         [-0.4227,  0.7728, -1.0021,  0.1159, -1.3010],
         [-0.0558, -0.1391,  0.1266, -0.7312, -0.2187]]])


In [5]:
z= torch.zeros([3,3], dtype=torch.int32)
print(z)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)


In [6]:
newTensor= torch.full((4, 3), 3.14,dtype= torch.float32)
print(newTensor)

tensor([[3.1400, 3.1400, 3.1400],
        [3.1400, 3.1400, 3.1400],
        [3.1400, 3.1400, 3.1400],
        [3.1400, 3.1400, 3.1400]])


In [12]:
#matriz de varias dimensiones

escalar=torch.randn(1)
vector=torch.zeros(1,10)
matriz=torch.ones(2,2)
tresdim=torch.randn(5,2,4)
print(tresdim.ndim)
print(tresdim.dtype)
print(tresdim.device)


3
torch.float32
cpu


In [13]:
torch.cuda.is_available()

True

In [8]:
torch.tensor([2,2])

tensor([2, 2])