In [9]:
#ejercicios de pytorch
import torch

In [10]:
#tensores , en si lo mismo que un array en numpy
V_data = [1, 2, 3, 4, 5]
V = torch.tensor(V_data)
print(V)

tensor([1, 2, 3, 4, 5])


In [11]:
x = torch.randn((3, 4, 5))
print(x)

tensor([[[-0.5941, -2.2063,  0.5739,  1.2033,  0.4311],
         [ 0.2627, -3.2469,  0.7036,  0.0250,  0.9762],
         [-2.3787,  0.6626,  0.6021, -0.3901, -0.7141],
         [-1.3435,  0.3579, -2.3185,  0.1093,  3.0322]],

        [[-0.2779, -3.3407, -0.3278, -2.2438, -1.1157],
         [-0.2015, -0.6515, -0.1435,  0.5974, -1.6184],
         [-0.0513, -0.2335,  0.4105, -0.9901, -0.7384],
         [-0.2432,  0.4167, -1.4882, -1.6144, -0.9662]],

        [[ 0.3384, -0.4125, -0.2614, -1.4303,  0.6686],
         [-0.3424,  0.7220, -1.2482,  1.2497,  0.5927],
         [ 1.1828,  0.6808, -1.3605, -0.7495, -0.4579],
         [-0.4365, -0.7817, -1.0217,  0.3818,  0.0448]]])


In [12]:
z= torch.zeros([3,3], dtype=torch.int32)
print(z)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)


In [13]:
newTensor= torch.full((4, 3), 3.14,dtype= torch.float32)
print(newTensor)

tensor([[3.1400, 3.1400, 3.1400],
        [3.1400, 3.1400, 3.1400],
        [3.1400, 3.1400, 3.1400],
        [3.1400, 3.1400, 3.1400]])
