In [1]:
#ejercicios de pytorch
import torch

In [2]:
#tensores , en si lo mismo que un array en numpy
V_data = [1, 2, 3, 4, 5]
V = torch.tensor(V_data)
print(V)

tensor([1, 2, 3, 4, 5])


In [3]:
x = torch.randn((3, 4, 5))
print(x)

tensor([[[-0.3022,  0.1457, -0.5088, -0.5207, -0.0424],
         [-2.9699,  0.6041,  0.2465,  0.8292, -0.3041],
         [ 0.0830, -1.3246, -0.6233,  2.0271,  0.6181],
         [ 0.1349,  2.5071, -0.1040, -1.6302, -0.8335]],

        [[ 0.3473,  1.3052, -0.2536, -1.3461,  0.4200],
         [ 0.4733, -0.2233, -1.6182,  0.0150,  0.5339],
         [-0.6108, -0.6831,  0.7273, -0.3121,  1.4868],
         [ 1.0587,  0.5607, -0.9027, -1.1002, -1.4115]],

        [[ 0.2621, -1.0525,  0.1541, -2.3346,  0.1285],
         [ 2.1342,  0.5870,  0.4405,  0.3479,  0.9167],
         [-1.3825, -1.8205, -0.1796,  0.6415, -1.7063],
         [-1.8089, -0.0096, -0.8542,  0.4676, -0.1519]]])


In [4]:
z= torch.zeros([3,3], dtype=torch.int32)
print(z)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)


In [5]:
newTensor= torch.full((4, 3), 3.14,dtype= torch.float32)
print(newTensor)

tensor([[3.1400, 3.1400, 3.1400],
        [3.1400, 3.1400, 3.1400],
        [3.1400, 3.1400, 3.1400],
        [3.1400, 3.1400, 3.1400]])


In [13]:
#matriz de varias dimensiones

escalar=torch.randn(1)
vector=torch.zeros(1,10)
matriz=torch.ones(2,2)
tresdim=torch.randn(5,2,4)
print(matriz.shape)


torch.Size([2, 2])


In [11]:
torch.tensor([2,2])

tensor([2, 2])